spring.application.name=All-API

# PostgreSQL für Railway
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=kSLwYSQgLIIddADgWtVEEVqrwxWxXxsS
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Railway Port
server.port=${PORT}
